### ISSUE TITLE
Leading comment does not show up as a token.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-javascript#4]
```java
    @Test
    void javaScriptDoc() {
        rewriteRun(
          javascript(
            """
              /**
               * @param {string} p1
               * @param {string} p2
               */
              function f ( p1, p2 ) {
              }
              """
          )
        );
    }
```

**Comment by knutwannheden** [comment]
Yes, this is extremely annoying. Didn't find any solution to this yet, either.

**Comment by traceyyoshima** [comment]
Update:

JS docs are a property on certain TSCNodes and may be retrieved through: `List<TSCNode> docNodes = node.getOptionalNodeListProperty("jsDoc");`

I'm unsure how the `whitespace()` method will need to change to accommodate a list of `TSCNode`, since source positions will be relevant.
