### ISSUE TITLE
Mass ingest JavaScript and TypeScript repos

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-javascript#88]
Steps:

- [x] Links to most starred projects:
         - [JavaScript](https://github.com/search?q=kotlin+language%3AJavaScript+&type=repositories&s=stars&o=desc)
         - [TypeScript](https://github.com/search?q=kotlin+language%3ATypeScript&type=repositories&s=stars&o=desc)
- [x] Add ingest jobs to Jenkins via [jenkins-ingest](https://github.com/moderneinc/jenkins-ingest).
         - Follow the steps in the readme.
- [x] Add the new repos to the SAAS organizations.

**Comment by timtebeek** [comment]
It looks like you might be able to reuse some of the logic we have in this script
https://github.com/moderneinc/jenkins-ingest/blob/f8bd018f7db67555a85c0a2e988049c8650c0191/add-github-organization.sh#L4-L11
But then substitute `gh search repos --language javascript --sort stars`

**Comment by traceyyoshima** [comment]
> https://github.com/moderneinc/jenkins-ingest/blob/f8bd018f7db67555a85c0a2e988049c8650c0191/add-github-organization.sh#L4-L11

Thank you!

**Comment by kunli2** [comment]
nice, thanks @timtebeek

**Comment by sjungling** [comment]
Better links for finding repos https://github.com/trending/javascript https://github.com/trending/typescript especially when you use the date range _1 month_

**Comment by kunli2** [comment]
I run this adjusted script 
```
gh search repos --language javascript --sort stars --visibility public --limit 10 --json name,owner,defaultBranch --template "{{range .}},{{.name}},{{.defaultBranch}},,,,,,,{{\"\n\"}}{{end}}" 

```
and got 
```
,casperjs,master,,,,,,,
,sw-precache,master,,,,,,,
,angular-loading-bar,master,,,,,,,
,hogan.js,master,,,,,,,
,Buttons,master,,,,,,,
,deployd,master,,,,,,,
,kraken-js,v2.x,,,,,,,
,PixelKit-Bootstrap-UI-Kits,master,,,,,,,
,cubism,master,,,,,,,
,colorbox,master,,,,,,,
``` 
Seems we need both owner and name to be able to ingest?

**Comment by sjungling** [comment]
@kunli2 might I suggest dropping the `star` sort and just let it sort by default (`best-match`) and if you add `--updated="> 2023-11-21"` you'll get more recent and active projects:

```
,react,main,,,,,,,
,javascript-algorithms,master,,,,,,,
,bootstrap,main,,,,,,,
,AutoGPT,master,,,,,,,
,javascript,master,,,,,,,
,30-seconds-of-code,master,,,,,,,
,next.js,canary,,,,,,,
,axios,v1.x,,,,,,,
,create-react-app,main,,,,,,,
,node,main,,,,,,,
```

**Comment by timtebeek** [comment]
Feel free to add the outcome above as a script to the jenkins-ingest project; likely not the last time we want to add popular recipes for a particular language (eyeing Python next for instance).

**Comment by kunli2** [comment]
note here for future reference: this is the script to generate import Json content, and need to add the header and tail.
```sh
gh search repos --language typescript --sort stars --visibility public --limit 10 --json fullName,defaultBranch --template '{{range .}}
    {
      "__typename": "GitHubRepository",
      "origin": "github.com",
      "path": "{{.fullName}}",
      "branch": "{{.defaultBranch}}"
    },{{""}}{{end}}'
```

**Comment by kunli2** [comment]
> Feel free to add the outcome above as a script to the jenkins-ingest project; likely not the last time we want to add popular recipes for a particular language (eyeing Python next for instance).

yes, added https://github.com/moderneinc/jenkins-ingest/pull/181/files

Also Thanks @sjungling , I removed the `star` sorting filter for a better fit.

**Comment by traceyyoshima** [comment]
the organization was updated today. Closing issue as finished -- ty @kunli2 !
